### ISSUE TITLE
Normalize latin letters/accents

### ISSUE THREAD

**Issue by pateketrueke** [apostrophecms/sluggo#1]
Firstly, fantastic library!

I'm trying this:

``` javascript
var s = require('sluggo');

console.log(s('¡Un avión!')); // outputs: un-avión
```

I expected: un-avion (without any accents)

**Comment by bfred-it** [comment]
This was my expectation of this library too. Maybe it should be specified that it's not for URLs

**Comment by boutell** [comment]
I don't think I understood the original ticket then. Is this about
misleading duplicates of Latin characters? Those would be worth addressing

**Comment by bfred-it** [comment]
No, my bad, I misread your first comment. I suppose that yes, this works in URLs
